### ISSUE TITLE
Unrecognized optional argument `upsert`

### ISSUE THREAD

**Issue by AvivLander** [fuwaneko/jugglingdb-rethink#26]
Some information for values removed for security... but this is the error presented:

Seems it's an issue with the new version of ReThinkDB: https://github.com/rethinkdb/rethinkdb/issues/2994

Unrecognized optional argument `upsert` in:\nr.db(\"test\").table(\"member\").insert({email: \"test3@test.test\", password: \"\", verificationToken: \"\", id: \"f46bdbbf-e493-4ccb-97d1-59e2153a2247\"}, {upsert: true})\n^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

at RqlCompileError.RqlServerError (/Users/avivcallander/node_modules/jugglingdb-rethink/node_modules/rethinkdb/errors.js:39:13)\n    at new RqlCompileError (/Users/avivcallander/node_modules/jugglingdb-rethink/node_modules/rethinkdb/errors.js:62:50)\n    at mkErr (/Users/avivcallander/node_modules/jugglingdb-rethink/node_modules/rethinkdb/util.js:157:10)\n    at TcpConnection.Connection._processResponse (/Users/avivcallander//node_modules/jugglingdb-rethink/node_modules/rethinkdb/net.js:135:16)\n    at TcpConnection.Connection._data (/Users/avivcallander/node_modules/jugglingdb-rethink/node_modules/rethinkdb/net.js:104:12)\n    at Socket.<anonymous> (/Users/avivcallander/node_modules/jugglingdb-rethink/node_modules/rethinkdb/net.js:523:32)\n    at Socket.EventEmitter.emit (events.js:95:17)\n    at Socket.<anonymous> (_stream_readable.js:746:14)\n    at Socket.EventEmitter.emit (events.js:92:17)\n    at emitReadable_ (_stream_readable.js:408:10)

**Comment by AvivLander** [comment]
https://github.com/rethinkdb/docs/issues/424

"upsert is now replace, and error/update are also available.

See rethinkdb/rethinkdb#1838 for more information."
